version: '3.8'

services:
  mariadb:
    build:
      context: ${PWD}/docker/mariadb
    container_name: cma_mariadb
    ports:
      - "3306:3306"
    expose:
      - 3306
    restart: on-failure
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file:
      - ./docker/mariadb/.mariadb.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ${MARIADB_VOLUME}/:/var/lib/mysql